const SUPABASE_URL = 'https://qtcrlxxzaranmvyohsdb.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Y3JseHh6YXJhbm12eW9oc2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzMjc4NDksImV4cCI6MjEwMTkwMzg0OX0.dxahqrteBVVfNfK6Snz_ocbgfpgYY_l6_mv0RjKuLB0';

const supabaseAdmin = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);